import type { NextPage } from 'next'
import Head from 'next/head'
import { Navbar } from '../components'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <h1>main</h1>
      </main>

      <footer className="bg-red-700">
        <h1 className="text-red-400">footer</h1>
      </footer>
    </div>
  )
}

export default Home
