import React from 'react'
import Head from 'next/head'
import css from './Layout.module.css'
import { Navbar, Footer } from '../../components'

type LayoutProps = {
  pageTitle: string
  children: React.ReactNode
}

export const Layout = ({ children, pageTitle }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={css.Main}>{children}</main>
      <Footer />
    </>
  )
}
