import React from 'react'
import Head from 'next/head'
import { Navbar } from '../../components'

type LayoutProps = {
  pageTitle: string
  children: JSX.Element
}

export const Layout = ({ children, pageTitle }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
      <footer>footer</footer>
    </>
  )
}
